### ISSUE TITLE
General brokenness between stateful & stateless APIs

### ISSUE THREAD

**Issue by ac000** [hmrc/income-tax-mtd-changelog#14]
As is explained in #3 the 'Self-Assessment' APi is stateful while the rest of the APis are stateless and is also evidenced in #3 that is causing issues.

Is there any time scale for either making the 'SelfAssessment' API stateless of just finish replacing it with new APIs?

I'm not sure how people are currently managing to test stuff in the current situation (without a lot of kludging, which negates the point of the sandbox environment somewhat).

**Comment by hmrc-api-team** [comment]
Hi @ac000,

We agree that the current testing solution is less than ideal. As you mentioned, the preferred outcome for us would be to completely replace the existing Self Assessment API monolith with a set of new APIs, and a fully stateless testing experience. It's difficult to give a timescale for this due to limited resources, but I can assure you that we are pushing at every available opportunity to get this work prioritised. In the meantime if you have any specific concerns about the existing stateful behaviour which we are still maintaining, or any additional stateless response scenarios you would like added to a particular API please do feel free to raise it and we will try our best to make the testing experience less painful where we can.

Kind regards,
MTD API Team

**Comment by hmrc-api-team** [comment]
@ac000 Somewhat relevantly, we do now have a delivery roadmap hosted on the developer hub which sets out the current anticipated schedule for future API releases -https://developer.service.hmrc.gov.uk/roadmaps/mtd-itsa-vendors-roadmap/
